---
title: "XAI3"
author: "Marc Vicedo Carboneres"
date: "24/5/2024"
output: html_document
---

```{r carga librerias necesarias}

library(dplyr)
library(plotly)
library(reshape2)
library(lubridate)
library(randomForestSRC)

```

```{r carga y transformación de datos para aplicar el modelo de random forest}

days <- read.csv("day.csv")
hour <- read.csv("hour.csv")

days$dteday <- as_date(days$dteday)
days_since <- select(days, workingday, holiday, temp, hum, windspeed, cnt)
days_since$days_since_2011 <- int_length(interval(ymd("2011-01-01"), days$dteday)) / (3600*24)
days_since$SUMMER <- ifelse(days$season == 3, 1, 0)
days_since$FALL <- ifelse(days$season == 4, 1, 0)
days_since$WINTER <- ifelse(days$season == 1, 1, 0)
days_since$MISTY <- ifelse(days$weathersit == 2, 1, 0)
days_since$RAIN <- ifelse(days$weathersit == 3 | days$weathersit == 4, 1, 0)
days_since$temp <- days_since$temp * 47 - 8
days_since$hum <- days_since$hum * 100
days_since$windspeed <- days_since$windspeed * 67

```


```{r we create the rf model and analyse the influence of days since 2011, temperature, humidity and wind speed on the predicted bike counts.}
rf_model <- rfsrc(cnt~., data=days_since)

output <- select(days_since, days_since_2011, temp, hum, windspeed, cnt)
num_rows <- nrow(days_since)
for(column in names(output)[1:4])
{
  for(index in 1:num_rows){
    temp_data <- days_since
    temp_data[[column]] <- days_since[[column]][index]
    prediction <- predict(rf_model, temp_data)$predicted
    output[[column]][index] <- sum(prediction) / num_rows
  }
}

```